FROM unfoldingword/obs-base:latest

# Which uWSGI .ini file should be used, to make it customizable
#ENV UWSGI_INI /app/obs-pdf/public/uwsgi.ini

# URL under which static (not modified by Python) files will be requested
# They will be served by Nginx directly, without being handled by uWSGI
#ENV STATIC_URL /output
# Absolute path in where the static files wil be
#ENV STATIC_PATH /app/obs-pdf/output
# Timeout in seconds for processing Flask requests
#ENV NGINX_TIMEOUT 300

# Define environment variables
ENV REDIS_URL redis://172.21.0.2:6379
ENV QUEUE_PREFIX dev-
ENV DEBUG_MODE True
# NOTE: The following environment variables are expected to be set for testing:
#	AWS_ACCESS_KEY_ID
#	AWS_SECRET_ACCESS_KEY
# NOTE: The following environment variables can be set:
#	QUEUE_PREFIX dev- (optional -- defaults to empty string)
#	DEBUG_MODE True (optional -- defaults to False)
#   REDIS_URL (optional -- defaults to 'redis://127.0.0.1:6379')
#   GRAPHITE_URL (optional -- defaults to 'localhost')

# install the obs-pdf app FROM GitHub
RUN cd /app \
    && git clone --single-branch -b develop https://github.com/unfoldingWord-dev/obs-pdf.git \
    && cd /app/obs-pdf \
    && git pull \
    && pip install --upgrade pip \
    && pip install --upgrade -r prerequisites.txt \
    && pip install -r requirements.txt

#COPY start_WebApp.sh /start_WebApp.sh
#COPY entrypoint.sh /entrypoint.sh

COPY start_RqApp_named.sh /start_RqApp_named.sh

CMD [ "/start_RqApp_named.sh" ]
