FROM unfoldingword/obs-base:latest

# Which uWSGI .ini file should be used, to make it customizable
#ENV UWSGI_INI /app/obs-pdf/public/uwsgi.ini

# URL under which static (not modified by Python) files will be requested
# They will be served by Nginx directly, without being handled by uWSGI
#ENV STATIC_URL /output
# Absolute path in where the static files wil be
#ENV STATIC_PATH /app/obs-pdf/output
# Timeout in seconds for processing Flask requests
#ENV NGINX_TIMEOUT 300

COPY . /app/obs-pdf/

# install the obs-pdf app
RUN cd /app/obs-pdf \
    && pip install --upgrade pip \
    && pip install --upgrade -r prerequisites.txt \
    && pip install -r requirements.txt
RUN cd /

#COPY resources/docker-app/start_WebApp.sh /start_WebApp.sh
#COPY resources/docker-app/entrypoint.sh /entrypoint.sh

COPY resources/docker-app/start_RqApp_named.sh /start_RqApp_named.sh
COPY resources/docker-app/start_RqApp_anon.sh /start_RqApp_anon.sh

# NOTE: No startup command here so you have to do it manually
#   i.e., /start_RqApp_anon.sh (lets RQ choose the worker name)
